# Generated by Django 4.2.1 on 2023-07-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0002_alter_pointofinterest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
