# Generated by Django 4.2.1 on 2023-07-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0003_alter_pointofinterest_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
