# Generated by Django 4.2.1 on 2023-07-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0003_alter_pointofinterest_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
