# Generated by Django 4.2.1 on 2023-07-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0004_delete_attachment_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='timestampAdded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
