# Generated by Django 4.2.1 on 2023-07-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0005_alter_pointofinterest_timestampadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
